export enum ItemTypes {
  TASK = "TASK",
}

export enum Position {
  ORIGINAL = "ORIGINAL",
  URGENT_IMPORTANT = "URGENT_IMPORTANT",
  NOT_URGENT_IMPORTANT = "NOT_URGENT_IMPORTANT",
  URGENT_NOT_IMPORTANT = "URGENT_NOT_IMPORTANT",
  NOT_URGENT_NOT_IMPORTANT = "NOT_URGENT_NOT_IMPORTANT",
}
